### PR TITLE
Added changelog, output to check if dropdown is open, option to allow space while mentioning, removed bootstrap dependency

### PR DESCRIPTION
**Pull request by pgedzba**
Fixes issues:
- #114 
- #109 
- #106

### CODE REVIEW

**Comment by ezintz** [comment]
Hello, I really like these changes. Would they also be working with Angular 7?

**Comment by pgedzba** [comment]
Yes, I have been working on this using Angular 7. The last thing I did was update dependencies. If you don't like this change you can revert this and it will still work :)

**Comment by shyamal890** [comment]
Aren't these changes merged yet?

**Comment by shyamal890** [comment]
@dmacfarlane Can you please merge these changes to master and release a new version

**Comment by pgedzba** [comment]
@dmacfarlane I have some more incoming pull requests after this one, but I'm waiting for this one to be merged. I'am going to use your library in my project, that's why I need the changes I'm making :)

**Comment by dmacfarlane** [comment]
This would be easier to review and merge if the features were in different PRs. I'd be happy to review a separate PR for #106 and one for #109 that uses 'opened' and 'closed' events.

**Comment by pgedzba** [comment]
Okay, I will fix it and create new PRs after weekend. My bad, sorry

**Pull request closed without merging**
