### PR TITLE
Upgrade to Angular 7

### PR DESCRIPTION
**Pull request by Alex61NN5**
- Updated HttpModule to HttpClientModule
- Upgraded to Angular 7
- Changed version number to 1.0.0
- Updated README.md to reflect the new changes on how install will work if you are running angular 5 and below use `npm install angular-mentions@0.9.0` if you are running angular 6 + use `npm install angular-mentions@1.0.0`

### CODE REVIEW

**Comment by Alex61NN5** [comment]
Tested and working on Chrome, Firefox and Safari (have not tested IE11)

**Comment by dmacfarlane** [comment]
Looks good, but can you revert the changes to the README and leave it unchanged?

**Comment by Alex61NN5** [comment]
Yep, sure can!

Thanks,
Alex

________________________________

**Comment by Alex61NN5** [comment]
I have reverted the README.md back to the original

**Comment by Alex61NN5** [comment]
Please merge pull request if you are happy, I would like to use this library in my angular 7 application.

**Comment by dmacfarlane** [comment]
Merged this manually to fix issue with package.json file.

**Pull request closed without merging**
