### PR TITLE
Return items with 'includes' searchTerm instead of 'startsWith'

### PR DESCRIPTION
**Pull request by FLoRyN1994**
Modified UpdateSearchList function to return items with 'includes' searchTerm instead of startsWith. 
@dmacfarlane , please take a look when you got some time. 

Thanks!

### CODE REVIEW

**Comment by ezintz** [comment]
Hello, any chance to get this pulled into a recent version? It is being open for long time and maintaining an own fork does not seem reasonable.

**Comment by jpsmedeiros** [comment]
I need this feature too, can someone please take a look at this?

**Comment by elTallarin** [comment]
any change of including this? Its very common to try to tag a user for example by name, last name, username.

**Comment by dmacfarlane** [comment]
This is one of the most requested features, so I hope to include it soon. Future updates to this will be tracked against #154.

Closing this PR in favor of #154 as the feature needs to be configurable along the lines of the "custom filter" search option in the angular material auto-complete component.

**Comment by TomJahncke** [comment]
Any progress on this (I realized it is closed) I also commented on #154. Does anyone know if this project is being actively worked on.  As @dmacfarlane mentioned this is one of the most requested features.

**Pull request closed without merging**
