### PR TITLE
Two new features.

### PR DESCRIPTION
**Pull request by smkamranqadri**
Added support for avatar in list and output event with complete object when select the item.

### CODE REVIEW

**Comment by dmacfarlane** [comment]
Closing old PR.

**Comment by smkamranqadri** [comment]
Is code merged?

**Comment by dmacfarlane** [comment]
No, the request is from 2017 and is out of date.

**Comment by smkamranqadri** [comment]
Will check with latest code.

**Comment by dmacfarlane** [comment]
The avatar support can be done using templates, see #111 for an example. Returning the selected object in an the event needs to be backwards compatible and address #97.

**Pull request closed without merging**
