### PR TITLE
Added event emitter to emit selected item from list

### PR DESCRIPTION
**Pull request by khan019950**
Added event emitter to emit selected item from list, whenever user select an item

### CODE REVIEW

**Comment by ehyecha** [comment]
@dmacfarlane  please merge it...
I need this feature. 
Thanks.

**Comment by khan019950** [comment]
@ehyecha  you can use https://www.npmjs.com/package/angular-mentions-v2

**Comment by sobhardwaj** [comment]
@khan019950  is that work with any input checkbox textarea ?? or any input field

**Comment by jimryanzulueta** [comment]
I'm having an issue onItemSelected. It says: `@Output onItemSelected not initialized in 'qn'`

**Comment by sobhardwaj** [comment]
> I'm having an issue onItemSelected. It says: `@Output onItemSelected not initialized in 'qn'`

there is another library for that u can do that...dont use this one

**Comment by dmacfarlane** [comment]
The event for this will be included in next release as part of #156.

**Pull request closed without merging**
