### PR TITLE
Add ability to insert HTML Elements

### PR DESCRIPTION
**Pull request by detaos**
HTML Elements can be inserted using a mentionSelect function that either returns an HTMLElement object or HTML code as a string.  See README changes for an example of both options.

### CODE REVIEW

**Comment by silentsnooc** [comment]
@dmacfarlane Any chance we'll see this?

**Comment by dmacfarlane** [comment]
I'd like to include a feature to insert HTML into a content-editable field, but I havn't been able to review or test these changes yet. Have you?

**Comment by silentsnooc** [comment]
@dmacfarlane Well, no. I don't think I am qualified for reviewing these changes since I am still quite inexperiences with Angular (and everything that comes with it). I'm actually not a web developer - a little handicap I bring with me. :D

**Comment by silentsnooc** [comment]
@dmacfarlane Ok, well .. I checked this out and I wouldn't say it's acceptable at this point. Deleting mentions with backspace is not working and moving the cursor around is also not very delighful as it sometimes jumps into the mentioned objects unfortunately.

Is there a chance you can point me to another repository here? I'm at a point where I don't know  what else I can type into the google searchbox..

**Comment by thecoconutstudio** [comment]
@silentsnooc  did you find anything on this?

**Comment by silentsnooc** [comment]
@thecoconutstudio Unfortunately not. I've decided to wait with this feature (although it's quite essential for my). However, you might want to take a look at this https://github.com/ianstormtaylor/slate

**Comment by detaos** [comment]
@silentsnooc, that's exactly what this patch enables ... if and only if you also set `insertHTML: true`.

The flag defaults to false, so you have to set it yourself:

`| insertHTML    | false    | Insert HTML instead of plain text. |`

```
[mentionConfig]="{
        insertHTML: true,
        mentionSelect: insertSpanText
}"
```

```
  /**
   * Note the trailig &nbsp;.
   * It helps with useability.
   */
  public insertSpanText(name) {
    return `
      <span
        class="mention"
        contenteditable="false"
        >@${name.label}</span>&nbsp;
    `;
  }
```

**Comment by khan019950** [comment]
@detaos is your proposal working like charm?

**Comment by Sakamotto** [comment]
Will this feature be merged?

**Comment by tibinvpaul** [comment]
It would be amazing to get this feature!

**Comment by elliot619** [comment]
Please make this feature possible, it would be very helpfull

**Comment by rishav0019** [comment]
@silentsnooc [100-Records.zip](https://github.com/dmacfarlane/angular-mentions/files/6389127/100-Records.zip)

**Pull request closed without merging**
